import { NextResponse } from 'next/server';

// Configure this in your .env.local:
// MURF_API_KEY=your_key_here

export async function POST(req: Request) {
  try {
    const { text, voiceId = 'en-US-natalie' } = await req.json();

    if (!text) {
      return NextResponse.json({ error: 'Text is required' }, { status: 400 });
    }

    const murfApiKey = process.env.MURF_API_KEY;
    if (!murfApiKey) {
      return NextResponse.json({ error: 'MURF_API_KEY is not configured.' }, { status: 500 });
    }

    // Call Murf AI Text-to-Speech API
    // Ensure you use the exact endpoint structure required by Murf
    const response = await fetch('https://api.murf.ai/v1/speech/generate', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'api-key': murfApiKey,
      },
      body: JSON.stringify({
        voiceId: voiceId,
        style: "Promo", // Example style, might need adjusting per voice
        text: text,
        format: "MP3"
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Murf API Error:', response.status, errorText);
      return NextResponse.json({ error: `Murf API Error: ${response.statusText}` }, { status: response.status });
    }

    const data = await response.json();
    
    // The response contains an audioFile URL
    if (data.audioFile) {
      const audioResponse = await fetch(data.audioFile);
      const audioBuffer = await audioResponse.arrayBuffer();
      
      return new NextResponse(audioBuffer, {
        headers: {
          'Content-Type': 'audio/mpeg',
          'Content-Length': audioBuffer.byteLength.toString(),
        },
      });
    } else {
      return NextResponse.json({ error: 'No audio generated by Murf API' }, { status: 500 });
    }
    
  } catch (error: any) {
    console.error('API Route Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
